# Site settings
title: Alan's Blog - Learning, Drilling and Upgrading
email: alantyqiao@163.com
description: >- # this means to ignore newlines until "baseurl:"
  A personal blog for sharing thoughts on coding, writing, language learning, etc.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alanciao.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  alanciao

# Build settings
markdown: kramdown
kramdown:
  input: GFM
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
